### ISSUE TITLE
tf issue

### ISSUE THREAD

**Issue by akul-g** [hasauino/rrt_exploration_tutorials#18]
Hi I came across this particular issue while trying to execute the single house simulation from the tutorial.

[ WARN] [1602527866.756874207, 2452.450000000]: Timed out waiting for transform from robot_1/base_footprint to robot_1/map to become available before running costmap, tf error: Could not find a connection between 'robot_1/map' and 'robot_1/base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.. canTransform returned after 0.1 timeout was 0.1.

The move base.launch file has the necessary listings but I can't seem to figure out what is causing the issue.
The view frame tf tree shows that the map is disconnected from the base_link.
Can you help me out here?

**Comment by hasauino** [comment]
Hi akul-g,
can you please show your tf tree?

**Comment by akul-g** [comment]
![Screenshot-Error-Final-tf-framse](https://user-images.githubusercontent.com/55465090/98119168-3e009100-1e7a-11eb-817e-6181716ca0a1.png)

This is the tf tree I'm currently looking at.

The odometry is not connected to the base frame which is causing the issue.

**Comment by hasauino** [comment]
What ROS distro. are you using?
Do you get any errors or warnings when calling this launch file?
The node which is responsible for publishing the transformation between the `base_link` and the `odom` is the Kobuki node.
So there is something wrong there. But I don't know why this is happening, I never had that error (on ROS Kinetic and Indigo).

**Comment by akul-g** [comment]
I'm currently using Kinetic maybe that's the issue

**Comment by hasauino** [comment]
Then it should work.
I assume you installed the required packages:
```
sudo apt-get install ros-kinetic-kobuki ros-kinetic-kobuki-core
sudo apt-get install ros-kinetic-kobuki-gazebo
sudo apt-get install ros-kinetic-gmapping
sudo apt-get install ros-kinetic-navigation
```
?
if you run the launch files that come with the ```kobuki-gazebo``` package, does it publish the frame transformation between the odom and the base_link normally?

**Comment by akul-g** [comment]
Hi Sorry for the late reply, so I realize that I was wrong when I mentioned I was on kinetic. I'm on Ubuntu 18 with ros melodic.

**Comment by hasauino** [comment]
No problem, I'll close this issue then

**Comment by akul-g** [comment]
Anyway to make it work on Melodic? It seems the only conflicting package is the kobuki bot

**Comment by hasauino** [comment]
This package was meant to quickly try out the `rrt_exploration` package. But there is another package which is even better, the turtlebot3 package, they also have turtlebo3_gazebo.. there you can find launch file to bring up the move base node, or the gmapping and other stuff

**Comment by akul-g** [comment]
Okay I'll look into that. The actual goal for my research is to try and implement rrt star on a bot within gazebo. So I wanted to work look at a working demo of path planning using something similar like your rrt_exploration package and learn from there onwards.

**Comment by hasauino** [comment]
the `rrt_exploration` package actually does not use RRT in path planning. We used it to detect unknown regions because of it's properties (it expands quickly)..
I found these papers very helpful when I implemented RRT:

[1]   Sampling-based Algorithms for Optimal Motion Planning
Sertac Karaman,  Emilio Frazzoli    (page 16) (this paper is enough but the other paper has more details, they sort of complement one other ).

[2]   Incremental Sampling-based Algorithms for Optimal Motion Planning
Sertac Karaman,  Emilio Frazzoli

If you want to look at my implementation (not good :p), it effectively starts from line 195 [here](https://github.com/hasauino/rrt_exploration/blob/master/src/global_rrt_detector.cpp#L192) , from line 216 - 230 is not part of RRT, it's just for our use case, where we mark unknown cells that are reached by the tree as exploration goals
